# This workflow will build wglinfo on Linux
name: Build (Linux/GCC)

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          g++ cmake ninja-build \
          libgl-dev libegl-dev \
          xvfb

    - name: Configure wglinfo
      run: |
        mkdir "build"
        cmake -G Ninja -D BUILD_TREAT_WARNINGS_AS_ERRORS=ON -S . -B "./build"

    - name: Build wglinfo
      run: |
        cmake --build "./build" --config Release

    - name: Run wglinfo
      run: |
        xvfb-run ./build/wglinfo
        xvfb-run ./build/wglinfo > wglinfo.log

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wglinfo-linux
        path: build/wglinfo
